import type { ProductRow } from "@/server/db/queries/workspace";

export const SAMPLE_PRODUCTS: ProductRow[] = [
  {
    id: "p1",
    importId: "preview-1",
    importFileName: "schneider-qo.xlsx",
    rowNumber: 1,
    rawMpn: "QO120",
    rawDescription: "20A 1P 120/240V plug-on circuit breaker",
    brand: "Square D",
    manufacturer: "Schneider Electric",
    productType: "Miniature Circuit Breaker",
    productName: "QO 20A 1-pole circuit breaker",
    proposedClasspath: "Electrical > Circuit Protection > Miniature Circuit Breakers",
    verifiedClasspath: "Electrical > Circuit Protection > Miniature Circuit Breakers",
    confidence: "HIGH",
    needsReview: false,
    isReady: true,
    imageUrl: "/products/product-qo120.png",
  },
  {
    id: "p2",
    importId: "preview-1",
    importFileName: "schneider-qo.xlsx",
    rowNumber: 2,
    rawMpn: "QO120CAFIC",
    rawDescription: "20A combination AFCI",
    brand: "Square D",
    manufacturer: "Schneider Electric",
    productType: "AFCI Circuit Breaker",
    productName: "QO 20A combination AFCI",
    proposedClasspath: "Electrical > Circuit Protection > AFCI Breakers",
    verifiedClasspath: null,
    confidence: "MEDIUM",
    needsReview: true,
    isReady: true,
    imageUrl: "/products/product-afci.png",
  },
  {
    id: "p3",
    importId: "preview-3",
    importFileName: "siemens-5sj.csv",
    rowNumber: 4,
    rawMpn: "5SJ4106-7HG41",
    rawDescription: "MCB 6A",
    brand: "Siemens",
    manufacturer: "Siemens",
    productType: "Miniature Circuit Breaker",
    productName: "5SJ 6A miniature circuit breaker",
    proposedClasspath: "Electrical > Circuit Protection > Miniature Circuit Breakers",
    verifiedClasspath: null,
    confidence: "HIGH",
    needsReview: false,
    isReady: true,
    imageUrl: "/products/product-mcb.png",
  },
  {
    id: "p4",
    importId: "preview-2",
    importFileName: "square-d-breakers.csv",
    rowNumber: 8,
    rawMpn: "QO115",
    rawDescription: "15A 1P breaker",
    brand: "Square D",
    manufacturer: "Schneider Electric",
    productType: "Miniature Circuit Breaker",
    productName: "QO 15A 1-pole circuit breaker",
    proposedClasspath: "Electrical > Circuit Protection > Miniature Circuit Breakers",
    verifiedClasspath: null,
    confidence: "HIGH",
    needsReview: false,
    isReady: true,
    imageUrl: "/products/product-qo115.png",
  },
];
